create table member
(
    id bigint generated by default as identity,
    pass varchar(255),
    primary key (id)
);

insert into member(pass) values('spring')
insert into member(pass) values('spring2')